<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FILTERS</name>
   <tag></tag>
   <elementGuidId>e93ab06c-4d8f-405e-a0f3-a3ee7156bcea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.filter_title__2iAJc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;FILTERS&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4bd6b15-f6c6-43a9-afed-f32614a04186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter_title__2iAJc</value>
      <webElementGuid>70926600-2ac9-4278-aaa8-a7889df853c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FILTERS</value>
      <webElementGuid>5209fe7e-5bf9-4ebc-8029-7b857bf67e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;dashboard_outbox__1Z8DY&quot;]/div[@class=&quot;dashboard_box__28Cgd&quot;]/div[@class=&quot;dashboard_filter__33JdN&quot;]/div[1]/div[@class=&quot;filter_outbox__25JPt&quot;]/div[@class=&quot;filter_box__b-oKa&quot;]/div[@class=&quot;filter_title__2iAJc&quot;]</value>
      <webElementGuid>e461a2c8-6469-4ed9-8df8-daf76f3aebc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>b3ed3556-72dd-4a62-85df-1a98328e38d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Products'])[1]/following::div[12]</value>
      <webElementGuid>5911d6e8-8130-4d25-856f-5aca16a5dbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zack Market'])[2]/following::div[22]</value>
      <webElementGuid>fc887cb8-19af-4bef-b9b5-681c73de7a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER'])[1]/preceding::div[2]</value>
      <webElementGuid>70fc31c9-ebe0-4cdb-bb14-c45c1d74617d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ascending'])[1]/preceding::div[4]</value>
      <webElementGuid>5bb34c17-ba3c-403d-9ee9-467f406807c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FILTERS']/parent::*</value>
      <webElementGuid>c6fb54b6-d1b7-4ce0-9854-36b0736307db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>bff20520-83f4-4669-8c61-9bdfde17a594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FILTERS' or . = 'FILTERS')]</value>
      <webElementGuid>ac396527-be15-4697-846d-0b8cd8e37bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
