<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Zack MarketWomenKidsMenAll Products</name>
   <tag></tag>
   <elementGuidId>fe3d2a5d-91ef-495f-90cd-a63bfa92ed8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header_content__1FFC7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Zack MarketWomenKidsMenAll Products&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01924f36-5f09-40fc-b9ba-aa01f5758f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_content__1FFC7</value>
      <webElementGuid>02cb0d32-9616-44bb-bc16-a7239bc0ce6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zack MarketWomenKidsMenAll Products</value>
      <webElementGuid>7e94b252-7f59-4b01-a33c-f32a08630584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;dashboard_outbox__1Z8DY&quot;]/div[@class=&quot;header_outbox__2AJDK&quot;]/div[@class=&quot;header_content__1FFC7&quot;]</value>
      <webElementGuid>db9354e3-f5c5-4b15-abb8-3d724b9d07e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]</value>
      <webElementGuid>88387e6a-2a0a-4f43-b5e3-ea8d3ea8be7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]</value>
      <webElementGuid>0f95b97c-4363-4aef-99e6-9ecf5f8b68cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Zack MarketWomenKidsMenAll Products' or . = 'Zack MarketWomenKidsMenAll Products')]</value>
      <webElementGuid>5799b0c4-1c04-4764-9362-795c9f989839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
